### ISSUE TITLE
UI Tab not loading

### ISSUE THREAD

**Issue by leifdreizler** [zidekmat/graphql_beautifier#2]
The UI tab isn't loading on v1.7.31 (on macOS) running Jruby 9.1.15.0.jar

There aren't any errors, it seems to load fine, just doesn't display.

**Comment by zidekmat** [comment]
I'll try to check it with that version. However, what headers are in your requests? Can you post it here?
As in JSON Beautifier, the tab shows only for appropriate content type `Content-Type: application/graphql` detected in the request.

**Comment by leifdreizler** [comment]
The content type is actually `content-type: application/json` which is probably why the tab isn't showing up. JSON Beautifier doesn't handle the GraphQL queries that well. Would it make sense for the tab to show up for any requests going to a /api/graphql endpoint? I'm not sure if that's possible or not. 

I'm testing this on app.segment.com which is free to signup for if you're looking for apps that rely heavily on GraphQL for testing 😬

**Comment by zidekmat** [comment]
It seems that I totally forgot about the fact that GraphQL queries can take JSON form so thanks for bringing this up.

I see the problem in fact that if I tried to beautify JSON and then it's `query` argument it would still make the request quite unreadable since JSON strings can't have newlines. It would look like this:
```
{
  "operationName": "getWorkspacesHomeData",
  "variables": {

  },
  "query": "query getSomethingSomething {\n  me {\n    id\n    something\n    name\n    email\n    somethings {\n      id\n      something\n      name\n      something\n      something\n      something {\n        something\n        something\n        __something\n      }\n      something {\n        id\n        something\n      }\n      something {\n        id\n        _something\n      }\n      something {\n        something\n        something\n        something\n        something\n        __something\n      }\n      __something\n    }\n    __something\n  }\n}"
}
```
I'll try to split the beautifier window into tree smaller ones for each of `operationName`, `variables`, `query` but I don't really know how to do that from Ruby so don't expect it any time soon. Sorry 😢

**Comment by leifdreizler** [comment]
Yeah, it would be cool to display it similarly to how the JSON Web Tokens UI tab works.
